// app/src/components/Login.tsx
import * as React from "react";
import classNames from "classnames";

import * as Requests from "../models/requests";
import { BaseProps } from "../types";
import { observable, action } from "mobx";
import { observer } from "mobx-react";

const emailRegex = /^([^\x00-\x20\x22\x28\x29\x2c\x2e\x3a-\x3c\x3e\x40\x5b-\x5d\x7f-\xff]+|\x22([^\x0d\x22\x5c\x80-\xff]|\x5c[\x00-\x7f])*\x22)(\x2e([^\x00-\x20\x22\x28\x29\x2c\x2e\x3a-\x3c\x3e\x40\x5b-\x5d\x7f-\xff]+|\x22([^\x0d\x22\x5c\x80-\xff]|\x5c[\x00-\x7f])*\x22))*\x40([^\x00-\x20\x22\x28\x29\x2c\x2e\x3a-\x3c\x3e\x40\x5b-\x5d\x7f-\xff]+|\x5b([^\x0d\x5b-\x5d\x80-\xff]|\x5c[\x00-\x7f])*\x5d)(\x2e([^\x00-\x20\x22\x28\x29\x2c\x2e\x3a-\x3c\x3e\x40\x5b-\x5d\x7f-\xff]+|\x5b([^\x0d\x5b-\x5d\x80-\xff]|\x5c[\x00-\x7f])*\x5d))*$/;

@observer
export class LoginComponent extends React.Component<BaseProps> {
  @observable
  email = "";
  @observable
  password = "";
  @observable
  persist = false;
  @observable
  errors: { [field: string]: string } = {};
  @observable
  validated = false;

  isValid(): boolean {
    return this.props.store.authStore.loginError == null;
  }

  @action
  validate(): boolean {
    this.errors = {};
    this.validated = true;

    if (!this.email) {
      this.errors["email"] = "Email is required";
    } else if (!emailRegex.test(this.email)) {
      this.errors["email"] = "Email is invalid";
    }

    if (!this.password || this.password.length < 6) {
      this.errors["password"] = "Password needs to be 6 or more characters";
    } else if (this.password && this.password.length > 50) {
      this.errors["password"] = "Password needs to be less than 50 characters";
    }

    return !Object.keys(this.errors).length;
  }

  @action.bound
  onSubmit(ev: any) {
    ev.preventDefault();
    if (this.validate()) {
      this.props.store.authStore.login(
        new Requests.Login(this.email, this.password, this.persist)
      );
    }
  }

  @action
  updateEmail(email: string) {
    this.email = email;
  }

  @action
  updatePassword(password: string) {
    this.password = password;
  }

  @action
  updatePersist(persist: boolean) {
    this.persist = persist;
  }

  renderLoginError() {
    if (this.props.store.authStore.loginError) {
      return (
        <div className="alert alert-danger">
          {this.props.store.authStore.loginError}
        </div>
      );
    }

    return null;
  }

  render() {
    const formClass = classNames("needs-validation");
    return (
      <div className="row">
        <div className="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-sm-12">
          <h3 className="text-center">Login to your account</h3>
          <br />
          {this.renderLoginError()}
          <form onSubmit={this.onSubmit.bind(this)} className={formClass}>
            <div className="form-group" key="1">
              <label htmlFor="email">Email:</label>
              <input
                className={classNames("form-control", {
                  "is-invalid": this.errors["email"]
                })}
                id="email"
                name="email"
                value={this.email}
                onChange={e => this.updateEmail(e.target.value)}
              />
              <span className="invalid-feedback">{this.errors["email"]}</span>
            </div>
            <div className="form-group" key="2">
              <label htmlFor="password">Password:</label>
              <input
                className={classNames("form-control", {
                  "is-invalid": this.errors["password"]
                })}
                id="password"
                name="password"
                type="password"
                value={this.password}
                onChange={e => this.updatePassword(e.target.value)}
              />
              <span className="invalid-feedback">
                {this.errors["password"]}
              </span>
            </div>
            <div className="form-row" key="3">
              <div className="col form-group">
                <div className="form-check">
                  <input
                    className="align-middle form-check-input"
                    id="rememberMe"
                    name="persist"
                    type="checkbox"
                    checked={this.persist}
                    value="persist"
                    onChange={e => this.updatePersist(e.target.checked)}
                  />
                  <label
                    className="form-check-label align-middle"
                    htmlFor="rememberMe"
                  >
                    Keep me logged in
                  </label>
                </div>
              </div>
              <div className="col form-group text-right">
                <a className="btn btn-link" href="/forgot-password">
                  I forgot my password
                </a>
              </div>
            </div>
            <div className="text-center" key="4">
              <button className="btn btn-primary" type="submit">
                Login
              </button>
              <span className="margin-small">or</span>
              <a href="/register">Register for a new account</a>
            </div>
          </form>
        </div>
      </div>
    );
  }
}

// app/src/components/login/login.component.ts
import { importCssAndHtml } from '../../loader.js';
import { authStore } from '../../stores/auth.store.js';
import { BaseComponent } from '../base.component.js';

const [css, html] = await importCssAndHtml(import.meta.url, 'login.component');

const emailRegex = /^([^\x00-\x20\x22\x28\x29\x2c\x2e\x3a-\x3c\x3e\x40\x5b-\x5d\x7f-\xff]+|\x22([^\x0d\x22\x5c\x80-\xff]|\x5c[\x00-\x7f])*\x22)(\x2e([^\x00-\x20\x22\x28\x29\x2c\x2e\x3a-\x3c\x3e\x40\x5b-\x5d\x7f-\xff]+|\x22([^\x0d\x22\x5c\x80-\xff]|\x5c[\x00-\x7f])*\x22))*\x40([^\x00-\x20\x22\x28\x29\x2c\x2e\x3a-\x3c\x3e\x40\x5b-\x5d\x7f-\xff]+|\x5b([^\x0d\x5b-\x5d\x80-\xff]|\x5c[\x00-\x7f])*\x5d)(\x2e([^\x00-\x20\x22\x28\x29\x2c\x2e\x3a-\x3c\x3e\x40\x5b-\x5d\x7f-\xff]+|\x5b([^\x0d\x5b-\x5d\x80-\xff]|\x5c[\x00-\x7f])*\x5d))*$/;

export class LoginComponent extends BaseComponent {
  private persist = false;
  private password = '';
  private email = '';

  passwordError = '';
  emailError = '';

  constructor() {
    super(html, css);

    this.subscribe(authStore.propChanged$, (prop) => {
      switch (prop) {
        case 'isLoggedIn':
        case 'loginError':
          this.digest();
          break;
      }
    });
  }

  get isLoggedIn() {
    return authStore.isLoggedIn;
  }

  get loginError() {
    return authStore.loginError;
  }

  emailChanged(event: InputEvent) {
    this.email = (event.target as HTMLInputElement)?.value;
    this.emailError = '';
  }

  passwordChanged(event: InputEvent) {
    this.passwordError = '';
    this.password = (event.target as HTMLInputElement)?.value;
  }

  rememberChanged(event: InputEvent) {
    if (event.target != null) {
      this.persist = (event.target as HTMLInputElement).checked;
    }
  }

  login(ev: Event) {
    ev.preventDefault();
    ev.stopPropagation();

    this.validateEmail();
    this.validatePassword();

    if (!this.emailError && !this.passwordError) {
      authStore.login({
        email: this.email,
        password: this.password,
        persist: this.persist,
      });
    }
  }

  validateEmail() {
    if (!this.email) {
      this.emailError = "Email is required";
    } else if (!emailRegex.test(this.email)) {
      this.emailError = "Email is invalid";
    }

    this.digest();
  }

  validatePassword() {
    if (!this.password || this.password.length < 6) {
      this.passwordError = "Password needs to be 6 or more characters";
    } else if (this.password && this.password.length > 50) {
      this.passwordError = "Password needs to be less than 50 characters";
    }

    this.digest();
  }
}

customElements.define('mds-login', LoginComponent);

<div class="row">
    <div class="col-lg-6 offset-lg-3 col-md-6 offset-md-3 col-sm-8 offset-sm-2 col-xs-12">
      <h3 class="text-center">Login to your account</h3>
      <br />
      <div [if]="this.loginError" class="alert alert-danger" [content]="this.loginError"></div>
      <form id="login_form" class="row g-3" [submit]="this.login(event)">
        <div class="col-12">
          <label class="form-label" for="email">Email:</label>
          <input
            class="form-control"
            [class]="this.emailError ? 'is-invalid' : ''"
            id="email"
            name="email"
            [change]="this.emailChanged(event)"
            [blur]="this.validateEmail()"
          />
          <div [if]="this.emailError" class="invalid-feedback" [content]="this.emailError"></div>
        </div>
        <div class="col-12">
          <label class="form-label" for="password">Password:</label>
          <input
            class="form-control"
            [class]="this.passwordError ? 'is-invalid' : ''"
            id="password"
            name="password"
            type="password"
            [blur]="this.validatePassword()"
            [change]="this.passwordChanged(event)"
          />
          <div [if]="this.passwordError" class="invalid-feedback" [content]="this.passwordError"></div>
        </div>
        <div class="col-6">
            <div class="form-check">
                <input
                  class="form-check-input"
                  id="rememberMe"
                  name="persist"
                  type="checkbox"
                  value="persist"
                  [change]="this.rememberChanged(event)"
                />
                <label
                  class="form-check-label"
                  for="rememberMe"
                >
                  Keep me logged in
                </label>
              </div>
        </div>
        <div class="col-6">
            <div class="col form-group text-end">
                <a class="text-decoration-none" href="/forgot-password">
                  I forgot my password
                </a>
              </div>
        </div>
        <div class="text-center">
          <button class="btn btn-primary" type="submit">
            Login
          </button>
          <span class="margin-small">or</span>
          <a class="text-decoration-none" href="/register">Register for a new account</a>
        </div>
      </form>
    </div>
  </div>
