// app/src/components/profile/profile.component.ts
import { importCssAndHtml } from '../../loader.js';
import { authStore } from '../../stores/auth.store.js';
import { BaseComponent } from '../base.component.js';

const [css, html] = await importCssAndHtml(import.meta.url, 'profile.component');

export class ProfileComponent extends BaseComponent {
  private emailTextbox!: HTMLInputElement;
  
  private confirm = '';
  private password = '';
  private email = '';

  passwordError = '';
  confirmError = '';

  constructor() {
    super(html, css);

    this.subscribe(authStore.propChanged$, (prop) => {
      switch (prop) {
        case 'saved':
        case 'saveError':
          this.digest();
          break;
      }
    });
  }

  get saved() {
    return authStore.saved;
  }

  get profileError() {
    return authStore.saveError;
  }

  connectedCallback() {
    super.connectedCallback();

    this.emailTextbox = this.root.querySelector('#email') as HTMLInputElement;
    this.emailTextbox.value = authStore.email || '';  
  }

  passwordChanged(ev: Event) {
    this.password = (ev.target as HTMLInputElement)?.value;
  }

  confirmChanged(ev: Event) {
    this.confirm = (ev.target as HTMLInputElement)?.value;
  }

  passwordFocused() {
    this.passwordError = '';
    this.confirmError = '';
    this.digest();
  }

  confirmFocused() {
    this.confirmError = '';
    this.digest();
  }

  validatePassword() {
    if (!this.password || this.password.length < 6) {
      this.passwordError = "Password needs to be 6 or more characters";
    } else if (this.password && this.password.length > 50) {
      this.passwordError = "Password needs to be less than 50 characters";
    }

    if (this.password !== this.confirm) {
      this.confirmError = "Passwords do not match";
    }

    this.digest();
  }

  updateProfile(ev: Event) {
    ev.preventDefault();
    ev.stopPropagation();

    if (!this.profileError && !this.passwordError) {
      authStore.updateProfile(this.password);
      (ev.target as HTMLFormElement)?.reset();
    }
  }
}

customElements.define('mds-profile', ProfileComponent);

<div class="row">
  <div class="col-lg-6 offset-lg-3 col-md-6 offset-md-3 col-sm-8 offset-sm-2 col-xs-12">
    <h3 class="text-center">Update Your Profile</h3>
    <br />
    <div [if]="this.profileError" class="alert alert-danger" [content]="this.profileError"></div>
    <div [if]="this.saved" class="alert alert-success">Profile Updated Successfully</div>
    <form id="profile_form" class="row g-3" [submit]="this.updateProfile(event)">
      <div class="col-12">
        <label class="form-label" for="email">Email:</label>
        <input class="form-control" id="email" name="email" disabled="disabled" />
      </div>
      <div class="col-12">
        <label class="form-label" for="password">Password:</label>
        <input class="form-control" [focus]="this.passwordFocused()" [blur]="this.validatePassword()"
          [change]="this.passwordChanged(event)" [classes]="{ 'is-invalid': this.passwordError }" id="password"
          name="password" type="password" />
        <div class="invalid-feedback" [content]="this.passwordError"></div>
      </div>
      <div class="col-12">
        <label class="form-label" for="password">Confirm Password:</label>
        <input class="form-control" [focus]="this.confirmFocused()" [blur]="this.validatePassword()"
          [change]="this.confirmChanged(event)" [classes]="{ 'is-invalid': this.confirmError }" id="confirm"
          name="confirm" type="password" />
        <div class="invalid-feedback" [content]="this.confirmError"></div>
      </div>
      <div class="text-center">
        <button class="btn btn-primary" type="submit" [classes]="{ disabled: this.confirmError || this.passwordError }">
          Save Changes
        </button>
      </div>
    </form>
  </div>
</div>

// app/src/components/Profile.tsx
import * as React from "react";
import classNames from 'classnames';
import { observable, when } from "mobx";
import { observer } from "mobx-react";

import * as Requests from "../models/requests";
import { BaseProps } from "../types";

interface ProfileProps {
  flux: any;
}

interface ProfileState {
  auth?: any;
  email?: string;
  password?: string;
  confirm?: string;
  errors?: any;
}

@observer
export class ProfileComponent extends React.Component<BaseProps> {
  @observable
  errors: { [field: string]: string } = {};
  @observable
  password = "";
  @observable
  confirm = "";
  @observable
  updateSuccess = false;

  isValid(): boolean {
    return !this.errors;
  }

  onSubmit(ev: any) {
    ev.preventDefault();
    if (this.validate()) {
      if (this.confirm == this.password) {
        this.props.store.authStore.updateProfile(this.password);
        when(
          () => !this.props.store.authStore.saving,
          () => {
            this.updateSuccess = this.props.store.authStore.saved;
            this.password = "";
            this.confirm = "";
          }
        );
      }
    }
  }

  passwordChanged(password: string) {
    this.password = password;
  }

  confirmChanged(password: string) {
    this.confirm = password;
  }

  validate(): boolean {
    this.errors = {};

    if (this.confirm != this.password) {
      this.errors["password"] = "passwords do not match";
      this.errors["confirm"] = "passwords do not match";
    } else if (!this.password || this.password.length < 6) {
      this.errors["password"] = "Password needs to be 6 or more characters";
    } else if (this.password && this.password.length > 50) {
      this.errors["password"] = "Password needs to be less than 50 characters";
    }

    return !Object.keys(this.errors).length;
  }

  renderProfileError() {
    if (this.props.store.authStore.saveError) {
      return (
        <div className="alert alert-danger">
          {this.props.store.authStore.saveError}
        </div>
      );
    }

    return null;
  }

  render() {
    return (
      <div className="row">
        <div className="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-sm-12">
          <h3 className="text-center">Update Your Profile</h3>
          <br />
          {this.renderProfileError()}
          {this.updateSuccess ? (
            <div className="alert alert-success">
              Profile Updated Successfully
            </div>
          ) : null}

          <form
            onSubmit={this.onSubmit.bind(this)}
            className="needs-validation"
          >
            <div className="form-group" key="1">
              <label className="control-label" htmlFor="email">
                Email:
              </label>
              <input
                className="form-control"
                id="email"
                name="email"
                defaultValue={this.props.store.authStore.email}
                disabled={true}
              />
            </div>
            <div className="form-group" key="2">
              <label className="control-label" htmlFor="password">
                Password:
              </label>
              <input
                className={classNames("form-control", { "is-invalid": this.errors["password"]})}
                id="password"
                name="password"
                type="password"
                value={this.password}
                onChange={e => this.passwordChanged(e.target.value)}
              />
              {this.errors["password"] ? (
                <span className="invalid-feedback">
                  {this.errors["password"]}
                </span>
              ) : null}
            </div>

            <div
              className="form-group"
              key="3"
            >
              <label className="control-label" htmlFor="password">
                Confirm Password:
              </label>
              <input
                className={classNames("form-control", { "is-invalid": this.errors["confirm"]})}
                id="confirm"
                name="confirm"
                type="password"
                value={this.confirm}
                onChange={e => this.confirmChanged(e.target.value)}
              />
              {this.errors["confirm"] ? (
                <span className="invalid-feedback">{this.errors["confirm"]}</span>
              ) : null}
            </div>
            <div className="text-center">
              <button className="btn btn-primary" type="submit">
                Save Changes
              </button>
            </div>
          </form>
        </div>
      </div>
    );
  }
}
