// app/src/components/search/search.component.ts
import { importCssAndHtml } from '../../loader.js';
import { BaseComponent } from '../base.component.js';

import { searchStore } from '../../stores/search.store.js';
import { toGoDateString, toLongDateString } from '../../util/date.js';

const [css, html] = await importCssAndHtml(import.meta.url, 'search.component');

export class SearchComponent extends BaseComponent {
  
  constructor() {
    super(html, css);

    this.subscribe(searchStore.propChanged$, (prop) => {
      switch (prop) {
        case 'searching':
        case 'searchResults':
        case 'searchError':
        case 'total':
        case 'offset':
          this.digest();
          break;
      }
    });
  }

  handlePageLink(offset: number, ev: MouseEvent) {
    if (offset == null) {
      ev.preventDefault();
      ev.stopPropagation();
    }
  }

  getShortDate(date: Date) {
    return toGoDateString(date);
  }

  getLongDate(date: Date) {
    return toLongDateString(date);
  }

  get nextOffset(): number | undefined { 
    return searchStore.nextOffset;
  }

  get prevOffset(): number | undefined { 
    return searchStore.prevOffset;
  }

  get offset(): number {
    return searchStore.offset;
  }

  get query(): string | null {
    return searchStore.query;
  }

  get searching(): boolean {
    return searchStore.searching;
  }

  get results() {
    return searchStore.searchResults;
  }

  get total() {
    return searchStore.total;
  }
}

customElements.define('mds-search', SearchComponent);

<div class="row">
    <div [if]="!this.searching" class="col-md-10 offset-md-1">
        <h4>
            <span [content]="this.total"></span> <span [content]="this.total > 1 ? 'results' : 'result'"></span> for "<span [content]="this.query"></span>"
        </h4>
        <div>
            <div [repeat]="result of this.results" class="card panel-default">
                <div class="card-body">
                    <span [content]="this.__index + 1 + this.offset + '.'"></span>
                    <a [href]="'/journal/' + this.getShortDate(this.result.date)"
                        [content]="this.getLongDate(this.result.date)"></a>
                    <!-- <a
                    href={
                    "/journal/" +
                    moment(result.date)
                        .utc()
                        .format("YYYY-M-D")
                    }
                >
                    {moment(result.date)
                    .utc()
                    .format("dddd, MMMM Do YYYY")}
                </a> -->
                </div>
                <ul class="list-group">
                    <li class="list-group-item" [repeat]="entry of this.result.entries">
                        <span [content]="this.entry"></span>
                    </li>
                </ul>
            </div>
        </div>
        <ul class="pager">
            <li class="previous">
                <a class="btn btn-link" [href]="`/search/${this.query}/${this.prevOffset}`"
                    [classes]="{ disabled: this.prevOffset == null }" [click]="this.prevPage()">
                    prev
                </a>
                <!-- 
                href={`/search/${this.props.store.searchStore.query}/${
                this.props.store.searchStore.prevOffset
                }`}
                class={classNames("btn", "btn-link", {
                disabled: this.props.store.searchStore.prevOffset == null
                })}
                onClick={this.handlePageLink.bind(
                this,
                this.props.store.searchStore.prevOffset
                )}
                rel={
                this.props.store.searchStore.prevOffset === null
                    ? "external"
                    : undefined
                }
            >
                <GoChevronLeft /> prev
            </a> -->
            </li>
            <li class="next">
                <a class="btn btn-link" [classes]="{ disabled: this.nextOffset == null }" [href]="`/search/${this.query}/${this.nextOffset}`" [click]="this.nextPage()">
                    next
                </a>
                
                <!-- <a class={classNames("btn", "btn-link" , { disabled:
                    this.props.store.searchStore.nextOffset==null })}
                    href={`/search/${this.props.store.searchStore.query}/${ this.props.store.searchStore.nextOffset }`}
                    onClick={this.handlePageLink.bind( this, this.props.store.searchStore.nextOffset )} rel={
                    this.props.store.searchStore.nextOffset===null ? "external" : undefined }>
                    next
                    <GoChevronRight />
                </a> -->
            </li>
        </ul>
    </div>

    <div class="col-md-8 col-md-offset-2" [if]="this.searching">
        <div class="mt-4">
            <div class="progress">
                <div class="progress-bar progress-bar-striped active" role="progressbar" style="width: 100%" />
            </div>
        </div>
    </div>
</div>

// app/src/components/Search.tsx
import * as React from "react";
import moment from "moment";
import { BaseProps } from "../types";
import { observer } from "mobx-react";
import { GoChevronLeft, GoChevronRight } from "react-icons/go";

@observer
export class SearchComponent extends React.Component<BaseProps> {
  componentWillUnmount() {
    this.props.store.searchStore.clear();
  }

  handlePageLink(offset: number, ev: React.MouseEvent) {
    if (offset == null) {
      ev.preventDefault();
      ev.stopPropagation();
    }
  }

  render() {
    return (
      <div className="row">
        {this.props.store.searchStore.query ? (
          <div className="col-md-10 offset-md-1">
            <h4>
              {this.props.store.searchStore.total} results for "
              {this.props.store.searchStore.query}"
            </h4>
            <div>
              {this.props.store.searchStore.searchResults.map(
                (result, index) => {
                  return (
                    <div className="card panel-default" key={index}>
                      <div className="card-body">
                        {index + 1 + this.props.store.searchStore.offset}.{" "}
                        <a
                          href={
                            "/journal/" +
                            moment(result.date)
                              .utc()
                              .format("YYYY-M-D")
                          }
                        >
                          {moment(result.date)
                            .utc()
                            .format("dddd, MMMM Do YYYY")}
                        </a>
                      </div>
                      <ul className="list-group">
                        {result.entries.map((entry, ii) => (
                          <li
                            className="list-group-item"
                            key={ii}
                            dangerouslySetInnerHTML={{ __html: entry }}
                          />
                        ))}
                      </ul>
                    </div>
                  );
                }
              )}
            </div>
            <ul className="pager">
              <li
                className={
                  "previous " +
                  (this.props.store.searchStore.prevOffset == null
                    ? "disabled"
                    : "")
                }
              >
                <a
                  href={`/search/${this.props.store.searchStore.query}/${
                    this.props.store.searchStore.prevOffset
                  }`}
                  onClick={this.handlePageLink.bind(
                    this,
                    this.props.store.searchStore.prevOffset
                  )}
                  rel={
                    this.props.store.searchStore.prevOffset === null
                      ? "external"
                      : undefined
                  }
                >
                  <GoChevronLeft /> prev
                </a>
              </li>
              <li
                className={
                  "next " +
                  (this.props.store.searchStore.nextOffset == null
                    ? "disabled"
                    : "")
                }
              >
                <a
                  href={`/search/${this.props.store.searchStore.query}/${
                    this.props.store.searchStore.nextOffset
                  }`}
                  onClick={this.handlePageLink.bind(
                    this,
                    this.props.store.searchStore.nextOffset
                  )}
                  rel={
                    this.props.store.searchStore.nextOffset === null
                      ? "external"
                      : undefined
                  }
                >
                  next <GoChevronRight />
                </a>
              </li>
            </ul>
          </div>
        ) : (
          <div className="col-md-8 col-md-offset-2">
            <div className="mt-4">
              <div className="progress">
                <div
                  className="progress-bar progress-bar-striped active"
                  role="progressbar"
                  style={{ width: "100%" }}
                />
              </div>
            </div>
          </div>
        )}
      </div>
    );
  }
}
