// app/src/components/Streak.tsx
import * as React from 'react';
import { observer } from 'mobx-react';
import 'bootstrap';
import { BaseProps } from "../types";

@observer
export class StreakComponent extends React.Component<BaseProps> {
    componentDidMount() {
        this.props.store.authStore.getStreak();
        // $('[data-toggle="tooltip"]').tooltip();
    }

    render() {
        let streak = this.props.store.authStore.streak != null ? this.props.store.authStore.streak : 0;

        return <span data-toggle="tooltip" data-placement="left" title="Number of contiguous entries over the last ten days">
            Streak {" "}
            <span className="badge badge-primary badge-pill">
                {streak} {" "}
                {streak >= 10 ? <span className="glyphicon glyphicon-star" /> : null}
            </span>
        </span>
    }
}

// app/src/components/streak/streak.component.ts
import { BaseComponent } from '../base.component.js';
import { importCssAndHtml } from '../../loader.js';
import { authStore } from '../../stores/auth.store.js';

const [css, html] = await importCssAndHtml(import.meta.url, 'streak.component');

export class StreakComponent extends BaseComponent {
  constructor() {
    super(html, css);
  }

  get streak() {
    return authStore.streak;
  }

  connectedCallback(): void {
    super.connectedCallback();
    this.subscribe(authStore.propChanged$, (prop) => {
      switch (prop) {
        case 'streakLoading':
        case 'streak':
          this.digest();
          break;
      }
    });
  }
}

customElements.define('mds-streak', StreakComponent);

<span data-toggle="tooltip" data-placement="left" title="Number of contiguous entries over the last ten days">
  Streak
  <span class="badge badge-primary badge-pill">
    <span [content]="this.streak"></span>
    <span [if]="this.streak >= 10" class="glyphicon glyphicon-star"></span>
  </span>
</span>
