// app/src/components/Journal.tsx
import * as React from "react";
import classNames from "classnames";
import { observable, action, when } from "mobx";
import { observer } from "mobx-react";
import DayPicker from "react-day-picker";
import { Manager, Reference, Popper } from "react-popper";
import marked from "marked";
import moment from "moment";
import { GoChevronRight, GoChevronLeft, GoX } from "react-icons/go";

import * as Requests from "../models/requests";
import { StreakComponent } from "./Streak";
import { BaseProps } from "../types";

import "react-day-picker/lib/style.css";
import { readAsUtcDate } from "../date.util";

@observer
export class JournalComponent extends React.Component<BaseProps> {
  @observable
  errors: { [field: string]: string } = {};
  @observable
  newEntry = "";
  @observable
  showCalendar = false;

  node: any;

  componentDidMount() {
    window.addEventListener("click", e => this.handleClickOutside(e), false);
    window.addEventListener("touchend", e => this.handleClickOutside(e), false);
  }

  componentWillUnmount() {
    window.removeEventListener("click", e => this.handleClickOutside(e), false);
    window.removeEventListener(
      "touchend",
      e => this.handleClickOutside(e),
      false
    );
  }

  @action
  handleClickOutside(ev: MouseEvent | TouchEvent) {
    if (this.node != null && !this.node.contains(ev.target)) {
      this.showCalendar = false;
    }
  }

  @action
  validate(validateEmpty = true): boolean {
    this.errors = {};

    if (this.newEntry.length > 500) {
      this.errors["newEntry"] = "Entry must be 500 characters or less";
    } else if (
      this.props.store.journalStore.current &&
      this.props.store.journalStore.current.entries.length >= 10
    ) {
      this.errors["newEntry"] = "Only 10 entries are allowed per day";
    } else if (this.newEntry.length <= 0 && validateEmpty) {
      this.errors["newEntry"] = "Entry cannot be blank";
    }

    return Object.keys(this.errors).length <= 0;
  }

  @action
  newEntryChanged(text: string) {
    this.newEntry = text;
    this.validate(false);
  }

  @action
  handleAddEntry = (ev: React.MouseEvent | React.FormEvent) => {
    ev.preventDefault();

    if (this.validate()) {
      if (this.props.store.journalStore.current != null) {
        this.props.store.journalStore.edit(
          new Requests.EditJournalEntry(
            this.newEntry,
            this.props.store.journalStore.current.entries.length
          )
        );

        when(
          () => !this.props.store.journalStore.editing,
          () => {
            if (this.props.store.journalStore.error == null) {
              this.newEntry = "";
            }
          }
        );
      } else {
        this.props.store.journalStore.add(this.newEntry);

        when(
          () => !this.props.store.journalStore.adding,
          () => {
            if (this.props.store.journalStore.error == null) {
              this.newEntry = "";
            }
          }
        );
      }
    }
  };

  handleEditEntry(entry: string, index: number, ev: Event) {
    this.props.store.journalStore.edit(
      new Requests.EditJournalEntry(entry, index)
    );
  }

  handleDeleteEntry(index: number, ev: React.MouseEvent) {
    if (this.props.store.journalStore.current != null) {
      if (this.props.store.journalStore.current.entries.length > 1) {
        this.props.store.journalStore.edit(
          new Requests.EditJournalEntry(null, index)
        );
      } else {
        this.props.store.journalStore.delete();
      }
    }
  }

  handleDeleteAll(ev: Event) {
    this.props.store.journalStore.delete();
  }

  handlePrev(ev: React.MouseEvent) {
    ev.preventDefault();
    const date = moment(this.props.store.journalStore.localDate);
    this.props.store.routeStore.setDate(date.subtract(1, "day").toDate());
  }

  handleNext(ev: React.MouseEvent) {
    ev.preventDefault();
    const date = moment(this.props.store.journalStore.localDate);
    this.props.store.routeStore.setDate(date.add(1, "day").toDate());
  }

  @action
  handleDateChange(date: Date) {
    date.setHours(0, 0, 0, 0);
    if (date <= new Date()) {
      this.props.store.routeStore.setDate(date);
      this.showCalendar = false;
    }
  }

  @action
  handleToggleCalendar(ev: React.MouseEvent) {
    ev.preventDefault();
    ev.stopPropagation();

    this.showCalendar = !this.showCalendar;
  }

  handleKeyDown = (ev: any) => {
    if ((ev.keyCode == 10 || ev.keyCode == 13) && ev.ctrlKey) {
      this.handleAddEntry(ev);
    }
  };

  handleBlur = (ev: any) => {
    this.validate();
  };

  renderEntries() {
    if (this.props.store.journalStore.current != null) {
      return (
        <div className="journal mt-4">
          {this.props.store.journalStore.current.entries.map(
            (e: string, index: number) => (
              <div className="card" key={index}>
                <button
                  className="btn btn-outline-secondary btn-sm btn-journal-delete"
                  key="delete"
                  onClick={ev => this.handleDeleteEntry(index, ev)}
                >
                  <GoX />
                </button>
                <div
                  className="card-body journal-entry"
                  dangerouslySetInnerHTML={{ __html: marked(e) }}
                />
              </div>
            )
          )}
        </div>
      );
    } else if (this.props.store.journalStore.started) {
      return <h3 className="text-center">No entries...try to remember!</h3>;
    } else {
      return (
        <div className="mt-4">
          <div className="progress">
            <div
              className="progress-bar progress-bar-striped active"
              role="progressbar"
              style={{ width: "100%" }}
            />
          </div>
        </div>
      );
    }
  }

  isHighlight(day: Date) {
    const date = readAsUtcDate(day).toISOString();
    return this.props.store.searchStore.isoEntryDates.indexOf(date) >= 0;
  }

  render() {
    var today = moment(this.props.store.journalStore.localDate);
    var next = moment(this.props.store.journalStore.localDate).add(1, "day");
    var prev = moment(this.props.store.journalStore.localDate).add(-1, "day");

    return (
      <div className="row">
        <div className="col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-sm-12">
          <div className="text-center journal-header">
            <button
              className={
                "btn btn-link " +
                (this.props.store.journalStore.loading ? "disabled" : "")
              }
              key="prev"
              onClick={e => this.handlePrev(e)}
            >
              <GoChevronLeft />
            </button>

            <Manager>
              <Reference>
                {({ ref }) => (
                  <button
                    type="button"
                    className="btn btn-link date-toggle"
                    ref={ref}
                    onClick={e => this.handleToggleCalendar(e)}
                  >
                    <h2>{today.format("ddd, MMM Do YYYY")}</h2>
                  </button>
                )}
              </Reference>
              {this.showCalendar ? (
                <Popper placement="bottom" eventsEnabled={true}>
                  {({ ref, style, placement, arrowProps }) => (
                    <div
                      className="daypicker-container"
                      ref={node => (this.node = node) && ref(node)}
                      style={style}
                      data-placement={placement}
                    >
                      <DayPicker
                        month={this.props.store.journalStore.localDate}
                        toMonth={new Date()}
                        modifiers={{ highlighted: day => this.isHighlight(day) }}
                        disabledDays={{ after: new Date() }}
                        selectedDays={this.props.store.journalStore.localDate}
                        onDayClick={e => this.handleDateChange(e)}
                      />
                      {/* <div
                        ref={arrowProps.ref}
                        style={arrowProps.style}
                        data-placement={placement}
                      /> */}
                    </div>
                  )}
                </Popper>
              ) : null}
            </Manager>

            <button
              className={
                "btn btn-link " +
                (this.props.store.journalStore.loading ? "disabled" : "")
              }
              key="next"
              style={{
                visibility: moment().diff(next) >= 0 ? "visible" : "hidden"
              }}
              onClick={ev => this.handleNext(ev)}
            >
              <GoChevronRight />
            </button>
          </div>

          {this.renderEntries()}

          <hr className="mt-4" />

          {this.props.store.journalStore.error ? (
            <div className="alert alert-danger">
              {this.props.store.journalStore.error}
            </div>
          ) : null}

          {!this.props.store.journalStore.current ||
          this.props.store.journalStore.current.entries.length < 7 ? (
            <form onSubmit={this.handleAddEntry}>
              <div className="form-group">
                <label className="control-label pull-left">
                  Add a new entry (markdown)
                </label>
                <label className="float-right">
                  <StreakComponent store={this.props.store} />
                </label>
                <textarea
                  placeholder="New entry..."
                  className={classNames("form-control", {
                    "is-invalid": this.errors["newEntry"]
                  })}
                  rows={4}
                  style={{ width: "100%" }}
                  value={this.newEntry}
                  onKeyDown={this.handleKeyDown}
                  onBlur={this.handleBlur}
                  maxLength={500}
                  onChange={ev => this.newEntryChanged(ev.target.value)}
                />
                <span className="invalid-feedback">{this.errors["newEntry"]}</span>
              </div>

              <button
                className={
                  "btn btn-primary " +
                  (Object.keys(this.errors).length || !this.newEntry
                    ? "disabled"
                    : "")
                }
                type="submit"
                onClick={this.handleAddEntry}
              >
                Add
              </button>
              <span className="margin-small">(or press ctrl + enter)</span>
            </form>
          ) : (
            <div className="alert alert-info">
              You've got {this.props.store.journalStore.current.entries.length}{" "}
              entries, that should cover it!
            </div>
          )}
        </div>
      </div>
    );
  }
}

// app/src/components/journal/journal.component.ts
import { importCssAndHtml } from '../../loader.js';
import { BaseComponent } from '../base.component.js';

import { journalStore } from '../../stores/journal.store.js';
import { router } from '../router.js';
import { toGoDateString } from '../../util/date-format.js';

import '../streak/streak.component.js';
import './entry.component.js';

const [css, html] = await importCssAndHtml(import.meta.url, 'journal.component');

export class JournalComponent extends BaseComponent {
  invalid = true;

  newEntry: string = '';

  constructor() {
    super(html, css);

    this.subscribe(journalStore.propChanged$, (prop) => {
      switch (prop) {
        case 'current':
        case 'error':
        case 'editing':
        case 'loading':
        case 'adding':
          this.digest();
          break;
      }
    });
  }

  get showNext(): boolean {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return journalStore.utcDate < today;
  }

  get entries(): string[] {
    return journalStore.current?.entries || [];
  }

  get newEntryError() {
    return journalStore.error;
  }

  get editing() {
    return journalStore.editing;
  }

  get loading() {
    return journalStore.loading;
  }

  get adding() {
    return journalStore.adding;
  }

  get fullDate(): string {
    return journalStore.utcDate.toLocaleDateString('en-us', {
      weekday: 'short',
      month: 'short',
      day: '2-digit',
      year: 'numeric'
    });
  }

  get isFull() {
    return this.entries.length >= 7;
  }

  addEntry(event: Event) {
    event.preventDefault();

    const submitForm = this.root.querySelector('form') as HTMLFormElement;
    if (journalStore.current != null) {
      journalStore.edit({
        entry: this.newEntry,
        index: this.entries.length
      }).then(() => {
        if (!journalStore.error) {
          this.newEntry = '';
          submitForm.reset();
          this.digest();
        }
      });
    } else {
      journalStore.add(this.newEntry).then(() => {
        if (!journalStore.error) {
          this.newEntry = '';
          submitForm.reset();
          this.digest();
        }
      });
    }
  }

  entryKeypress(event: KeyboardEvent) {
    if (event.ctrlKey && event.code === 'Enter' && this.newEntry) {
      this.addEntry(event);
    }
  }

  entryChanged(event: Event) {
    if (event.target instanceof HTMLTextAreaElement) {
      this.newEntry = event.target.value;
      this.invalid = this.newEntry.length > 500 || this.newEntry.length === 0;
      this.digest();
    }
  }

  handlePrev(event: PointerEvent) {
    const newDate = new Date(journalStore.utcDate);
    newDate.setDate(journalStore.utcDate.getDate() - 1);
    router.navigate('/journal/' + toGoDateString(newDate));
    this.digest();
  }

  handleNext(event: PointerEvent) {
    const newDate = new Date(journalStore.utcDate);
    newDate.setDate(journalStore.utcDate.getDate() + 1);
    router.navigate('/journal/' + toGoDateString(newDate));
    this.digest();
  }
}

customElements.define('mds-journal', JournalComponent);

<div class="row">
    <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-sm-12">
        <div class="d-flex justify-content-between journal-header">
            <button class="btn btn-link" [classes]="{ 'disabled': this.isLoading }" [click]="this.handlePrev(event)">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="100%" fill="currentColor"
                    class="bi bi-chevron-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                        d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z" />
                </svg>
            </button>
            <h2 [content]="this.fullDate"></h2>

            <!-- <Manager>
                <Reference>
                    {({ ref }) => (
                    <button type="button" class="btn btn-link date-toggle" ref={ref} onClick={e=>
                        this.handleToggleCalendar(e)}
                        >
                        <h2>{today.format("ddd, MMM Do YYYY")}</h2>
                    </button>
                    )}
                </Reference>
                {this.showCalendar ? (
                <Popper placement="bottom" eventsEnabled={true}>
                    {({ ref, style, placement, arrowProps }) => (
                    <div class="daypicker-container" ref={node=> (this.node = node) && ref(node)}
                        style={style}
                        data-placement={placement}
                        >
                        <DayPicker month={this.props.store.journalStore.localDate} toMonth={new Date()} modifiers={{
                            highlighted: day=> this.isHighlight(day) }}
                            disabledDays={{ after: new Date() }}
                            selectedDays={this.props.store.journalStore.localDate}
                            onDayClick={e => this.handleDateChange(e)}
                            />
                            {/*
                            <div ref={arrowProps.ref} style={arrowProps.style} data-placement={placement} /> */}
                    </div>
                    )}
                </Popper>
                ) : null}
            </Manager> -->

            <!-- TODO: Hide button when at current date -->
            <button class="btn btn-link" [classes]="{ 'disabled': this.isLoading }" [click]="this.handleNext(event)">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="100%" fill="currentColor"
                    class="bi bi-chevron-right" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                        d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z" />
                </svg>
            </button>
        </div>

        <!-- {this.renderEntries()} -->
        <div className="journal mt-4">
            {this.props.store.journalStore.current.entries.map(
              (e: string, index: number) => (
                <div className="card" key={index}>
                  <button
                    className="btn btn-outline-secondary btn-sm btn-journal-delete"
                    key="delete"
                    onClick={ev => this.handleDeleteEntry(index, ev)}
                  >
                    <GoX />
                  </button>
                  <div
                    className="card-body journal-entry"
                    dangerouslySetInnerHTML={{ __html: marked(e) }}
                  />
                </div>
              )
            )}
          </div>


        <hr class="mt-2" />

        <div [if]="this.saveError" class="alert alert-danger" [content]="this.saveError">
        </div>

        <form [if]="!this.isFull" [submit]="this.addEntry(event)">
            <div class="form-group">
                <label class="control-label pull-left">
                    Add a new entry (markdown)
                </label>
                <label class="float-right">
                    <StreakComponent store={this.props.store} />
                </label>
                <textarea placeholder="New entry..."
                    class="form-control"
                    [classes]="{ 'is-invalid': this.newEntryError }" rows="4" style="width: 100%"
                    maxLength="500" change="this.updateEntryText(event)"></textarea>
                <span class="invalid-feedback" [content]="this.newEntryError"></span>
            </div>

            <button class="btn btn-primary" [classes]="{ disabled: this.invalid }" type="submit">
                Add
            </button>
            <span class="margin-small">(or press ctrl + enter)</span>
        </form>
        <div [if]="this.isFull" class="alert alert-info">
            You've got <span [content]="this.entries.length"></span>
            entries, that should cover it!
        </div>
    </div>
</div>
